-- 개선된 방식

SELECT A.CAR_ID, A.CAR_TYPE, FLOOR(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
        ON A.CAR_TYPE = C.CAR_TYPE
WHERE (A.CAR_TYPE = 'SUV'
    OR A.CAR_TYPE = '세단')
    AND A.CAR_ID NOT IN (
            SELECT DISTINCT B.CAR_ID 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
            WHERE B.START_DATE<='2022-11-30' AND B.END_DATE>='2022-11-01'
        )
    AND A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100 >= 500000
    AND A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100 < 2000000
    AND C.DURATION_TYPE = '30일 이상'
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
